plugins {
    id 'net.neoforged.moddev'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Dependencies go here
    implementation project(":MCULib")
    implementation "curse.maven:curios-309927:${curios_fileid}"
    implementation "curse.maven:modonomicon-538392:${modonomicon_fileid}"
    //compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}:api"
    //localRuntime "vazkii.patchouli:Patchouli:${patchouli_version}"

    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    // We add the full version to localRuntime, not runtimeOnly, so that we do not publish a dependency on it
    localRuntime "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    // Ultimine for testing
    localRuntime "curse.maven:ftb-ultimine-forge-386134:8078515"
    localRuntime "curse.maven:architectury-api-419699:5786327"
    localRuntime "curse.maven:ftb-library-forge-404465:7746959"

    // BWG and deps for sawmill integration
    implementation "curse.maven:oh-the-biomes-weve-gone-1070751:5932848"
    implementation "curse.maven:corgilib-693313:5691275"
    implementation "curse.maven:geckolib-388172:5874016"
    implementation "curse.maven:oh-the-trees-youll-grow-962544:5691181"
    implementation "curse.maven:terrablender-neoforge-940057:5864140"

    //Ars Nouveau
    implementation "curse.maven:ars-nouveau-401955:5995085"
    implementation "curse.maven:ars-elemental-561470:6006174"

    // Apotheosis
    implementation "curse.maven:apotheosis-313970:6545942"
    implementation "curse.maven:apothic-attributes-898963:6514649"
    implementation "curse.maven:apothic-enchanting-1063926:6514634"
    implementation "curse.maven:apothic-spawners-986583:6430294"
    implementation "curse.maven:placebo-283644:6446766"

    // Silent Gear
    implementation "curse.maven:silent-gear-297039:8095210"
    implementation "curse.maven:silent-lib-242998:7935618"

    // Occultism
    implementation "curse.maven:occultism-361026:8037152"
    implementation "curse.maven:smartbrainlib-661293:7055149"

    // Integrated Dynamics
    implementation "curse.maven:integrated-dynamics-236307:8126880"
    implementation "curse.maven:cyclops-core-232758:8006281"
    implementation "curse.maven:common-capabilities-247007:7756804"
    implementation "curse.maven:refined-storage-243076:8105115"

    // Jade
    implementation "curse.maven:jade-324717:7545219"

    // Malum
    implementation "curse.maven:malum-484064:7307339"
    implementation "curse.maven:lodestone-616457:7264731"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description,
            mculib_version          : mculib_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata
