## Mod Properties

mculib_version=1.5.2
jei_version=19.21.0.247
#patchouli_version=1.21-87-NEOFORGE
curios_fileid=6529130
modonomicon_fileid=7771524

mod_id=processenhancement
mod_name=Process Enhancement
mod_license=Apache License 2.0
mod_version=1.11
mod_group_id=com.mcupdater.processenhancement
mod_authors=smbarbour,allaryin
mod_description=Yet another technology mod, but this one is from the developers of MCUpdater