modLoader="javafml"
loaderVersion="[41,)"
license="Apache License Version 2.0"
issueTrackerURL="https://github.com/MCUpdater-Mods/Process-Enhancement/issues"
[[mods]]
modId="processenhancement"
version="${version}"
displayName="Process Enhancement"
authors="smbarbour, allaryin"
description='''
Yet another technology mod, but this one is from the developers of MCUpdater
'''
[[dependencies.processenhancement]]
modId="mculib"
mandatory=true
versionRange="[1.4,)"
ordering="NONE"
side="BOTH"
